# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14e25cb7-1e85-41f0-a4ac-e396a58696b3";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0D2D-8D86";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/media/games" =
    { device = "/dev/disk/by-uuid/062AB6DB2AB6C6C9";
      fsType = "ntfs3";
    };

  fileSystems."/media/fordocs" =
    { device = "/dev/disk/by-uuid/70CA5A11CA59D3C6";
      fsType = "ntfs3";
    };

  fileSystems."/media/forgames" =
    { device = "/dev/disk/by-uuid/E0460FB0460F868E";
      fsType = "ntfs3";
    };

  swapDevices = [ ];

  #nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
